Repository Vonage/vonage-java-sdk, pull requests merged in 2020-10, with the labels that each got.

#310 Removed @author from the following files
  CONTRIBUTORS.md
  src/main/java/com/vonage/client/auth/MD5Util.java
  src/main/java/com/vonage/client/sms/HexUtil.java
  src/main/java/com/vonage/client/sms/callback/AbstractMOServlet.java
  src/main/java/com/vonage/client/sms/callback/messages/MO.java
  src/main/java/com/vonage/client/sms/messages/Message.java
  src/main/java/com/vonage/client/sms/messages/TextMessage.java
  src/main/java/com/vonage/client/sms/messages/WapPushMessage.java
  src/main/java/com/vonage/client/sns/response/SnsSubscribeResponse.java
  src/main/java/com/vonage/client/verify/BaseResult.java
Labels: Hacktoberfest

#338 remove this keyword in listapplicationrequest.java
  CONTRIBUTORS.md
  src/main/java/com/vonage/client/application/ListApplicationRequest.java
Labels: Hacktoberfest, Status: In Review

#307 Removed unneeded _this_ keywords
  CONTRIBUTORS.md
  src/main/java/com/vonage/client/VonageClient.java
Labels: Hacktoberfest, Status: Changes Requested, Status: In Review

#311 Removed unnecessary references to the this keyword
  CONTRIBUTORS.md
  src/main/java/com/vonage/client/account/AccountClient.java
  src/main/java/com/vonage/client/account/PrefixPricingEndpoint.java
  src/main/java/com/vonage/client/account/PricingEndpoint.java
  src/main/java/com/vonage/client/account/SecretManagementEndpoint.java
  src/main/java/com/vonage/client/account/SettingsEndpoint.java
  src/main/java/com/vonage/client/account/TopUpEndpoint.java
Labels: Hacktoberfest

#316 Removed unnecessary this references from 2 files as mentioned in description
  CONTRIBUTORS.md
  src/main/java/com/vonage/client/application/ApplicationClient.java
  src/main/java/com/vonage/client/application/ApplicationEndpoint.java
Labels: Hacktoberfest, Status: Changes Requested, Status: In Review

#325 Prasanna | Removed unnecessary references to the "this" keyword
  src/main/java/com/vonage/client/application/Application.java
  src/main/java/com/vonage/client/application/capabilities/Messages.java
  src/main/java/com/vonage/client/application/capabilities/Rtc.java
  src/main/java/com/vonage/client/application/capabilities/Voice.java
Labels: Hacktoberfest

#320 Removing unnecessary references to the this keyword on XmlParser
  CONTRIBUTORS.md
  src/main/java/com/vonage/client/legacyutils/XmlParser.java
  src/main/java/com/vonage/client/numbers/NumbersClient.java
  src/main/java/com/vonage/client/numbers/SearchNumbersEndpoint.java
  src/main/java/com/vonage/client/numbers/UpdateNumberRequest.java
Labels: Hacktoberfest

#326 Changed WapPushMessage.java
  CONTRIBUTORS.md
  src/main/java/com/vonage/client/sms/messages/WapPushMessage.java
Labels: Hacktoberfest

#332 Update SmsSubmissionResponse.java
  src/main/java/com/vonage/client/sms/SmsSubmissionResponse.java
Labels: Hacktoberfest, Status: In Review

#333 Remove unnecessary references to `this`
  src/main/java/com/vonage/client/auth/TokenAuthMethod.java
Labels: Hacktoberfest

#343 Remove unnecessary references to the "this" keyword
  CONTRIBUTORS.md
  src/main/java/com/vonage/client/auth/AuthCollection.java
  src/main/java/com/vonage/client/sms/SmsDateSearchRequest.java
Labels: Hacktoberfest

#345 Remove unnecessary references to the "this" keyword.
  CONTRIBUTORS.md
  src/main/java/com/vonage/client/verify/CheckEndpoint.java
  src/main/java/com/vonage/client/verify/CheckResponse.java
Labels: Hacktoberfest

#346 Remove unnecessary references to the "this" keyword
  CONTRIBUTORS.md
  src/main/java/com/vonage/client/AbstractMethod.java
  src/main/java/com/vonage/client/HttpConfig.java
Labels: Hacktoberfest

#304 Fix: Error from no-content responses
  src/main/java/com/vonage/client/logging/LoggingUtils.java
  src/test/java/com/vonage/client/LoggingUtilTest.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#350 API Support
  README.md
Labels: Status: Ready for review

#351 Fix test failures on windows
  .gitattributes
  .github/workflows/build.yml
  CONTRIBUTORS.md
  src/test/java/com/vonage/client/VonageClientTest.java
  src/test/java/com/vonage/client/voice/ncco/NccoTest.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#347 Added Calendar.NOVEMBER instead of 10 Magic constant
  src/test/java/com/vonage/client/sms/callback/AbstractMOServletTest.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#328 Added new POJO for NotifyEvent as mentioned and added test cases for it as well
  CONTRIBUTORS.md
  src/main/java/com/vonage/client/incoming/NotifyEvent.java
  src/test/java/com/vonage/client/incoming/NotifyEventTest.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#327 Remove unnecessary reference of this keyword
  src/main/java/com/vonage/client/sms/SmsSubmissionResponseMessage.java
  src/main/java/com/vonage/client/sns/request/SnsRequest.java
  src/main/java/com/vonage/client/sns/response/SnsResponse.java
  src/main/java/com/vonage/client/sns/response/SnsSubscribeResponse.java
Labels: Hacktoberfest, Hacktoberfest-accepted

#334 Remove unnecessary references to the "this" keyword
  CONTRIBUTORS.md
  src/main/java/com/vonage/client/auth/JWTAuthMethod.java
  src/main/java/com/vonage/client/auth/VonageUnacceptableAuthException.java
  src/main/java/com/vonage/client/conversion/ConversionClient.java
  src/main/java/com/vonage/client/conversion/ConversionEndpoint.java
  src/main/java/com/vonage/client/insight/AdvancedInsightRequest.java
  src/main/java/com/vonage/client/insight/InsightClient.java
  src/main/java/com/vonage/client/insight/StandardInsightRequest.java
  src/main/java/com/vonage/client/sms/MessageStatus.java
  src/main/java/com/vonage/client/sms/SearchRejectedMessagesRequest.java
  src/main/java/com/vonage/client/sms/SmsIdSearchRequest.java
  src/test/java/com/vonage/client/auth/JWTAuthMethodTest.java
  src/test/java/com/vonage/client/conversion/ConversionClientTest.java
  src/test/java/com/vonage/client/insight/InsightClientTest.java
Labels: Hacktoberfest
